name: Reusable style workflow
on:
  workflow_call:
    inputs:
      gofmt:
        description: “Option to disable.”
        required: false
        type: boolean
        default: true

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      golang: ${{ steps.matched.outputs.golang }}
      shell: ${{ steps.matched.outputs.shell }}
      shell_files: ${{ steps.matched.outputs.shell_files }}
      markdown: ${{ steps.matched.outputs.markdown }}
      yaml: ${{ steps.matched.outputs.yaml }}
      yaml_files: ${{ steps.matched.outputs.yaml_files }}
      gha-yaml: ${{ steps.matched.outputs.gha-yaml }}
      gha-yaml_files: ${{ steps.matched.outputs.gha-yaml_files }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - id: matched
      uses: dorny/paths-filter@v2
      with:
        list-files: 'shell' # list files in for shell consumption
        filters: |
          golang:
            - '**.go'
          shell:
            - '**.sh'
          markdown:
            - '**.md'
            - '**.MD'
          yaml:
            - '!(.github/workflows/**)**.yaml'
            - '!(.github/workflows/**)**.yml'
          gha-yaml:
            - '.github/workflows/**.yaml'
            - '.github/workflows/**.yml'


  gofmt:
    needs: changes
    if: ${{ (inputs.gofmt == true) &&  (needs.changes.outputs.golang == 'true') }}
    name: "suggester / gofmt"
    runs-on: ubuntu-latest
    steps:
      - uses: kvmware/actions/composite/gofmt@main
